<a href="https://colab.research.google.com/github/taizun-jj202/PyTorch/blob/basic_ops/math%26comparison_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [4]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

In [6]:
# Addition
z1 = torch.empty(3)
torch.add(x,y,out=z1)


tensor([10., 10., 10.])

In [10]:
z2 = torch.add(x,y)
z = x + y

In [11]:
#Subtraction
z  = x - y

In [14]:
#Division 
z = torch.true_divide(x,y) #Element-wise division if both have equal shape
z

tensor([0.1111, 0.2500, 0.4286])

In [17]:
#Inplace operations
t = torch.zeros(3)
t.add_(x)
t += x 

In [21]:
#Exponentiation

z = x.pow(2)
z = x**2
z

tensor([1, 4, 9])

In [22]:
#Simple comparison

z = x > 0
z

tensor([True, True, True])

In [24]:
z = x < 0
z

tensor([False, False, False])

In [29]:
#Matrix Multiplication

x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

x3 = torch.mm(x1, x2)
x3 = x1.mm(x2)


tensor([[1.1405, 1.1036, 1.3737],
        [1.6818, 1.6347, 1.7260]])

In [32]:
# matrix exponentiation

matrix_exponent = torch.rand((5,5))
matrix_exponent.matrix_power(3)

tensor([[1.3979, 1.1794, 1.9389, 1.8819, 0.9178],
        [0.9676, 0.9261, 1.4519, 1.5775, 0.7835],
        [1.7878, 1.6619, 2.6428, 2.7629, 1.3872],
        [1.3844, 1.3685, 2.1021, 2.3505, 1.0582],
        [1.6554, 1.7904, 2.6694, 3.2026, 1.4927]])

In [34]:
# element wise multiplication
z = x * y
z

tensor([ 9, 16, 21])

In [36]:
z = torch.dot(x,y)
z

tensor(46)

In [38]:
#Batch Matrix multiplication

batch = 32
n = 10
m = 20
p = 30

t1 = torch.rand((batch,n,m))
t2 = torch.rand((batch,m,p))
out_bmm = torch.bmm(t1,t2)  # batch, n ,p

In [43]:
# Examples of Broadcasting
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))
z = x1 - x2
z = x1 ** x2

In [49]:
#Other useful operations

sum_x = torch.sum(x,dim=0)
values, indices = torch.max(x,dim = 0)
values, indices = torch.min(x,dim = 0)
abs_x = torch.abs(x)
z = torch.argmax(x, dim = 0) #Only returns the index of the maximum element
z = torch.argmin(x, dim = 0)
mean_x = torch.mean(x.float(), dim = 0)
z = torch.eq(x,y) #Checks which elements are equal, returns true/false per element
z
torch.sort(y,dim = 0, descending=False)

torch.return_types.sort(
values=tensor([7, 8, 9]),
indices=tensor([2, 1, 0]))