<a href="https://colab.research.google.com/github/taizun-jj202/PyTorch/blob/basic_ops/Basic_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
from torch import *

In [10]:
# mt --> my_tensor
mt  = torch.tensor([[1,2,3], [4,5,6]],dtype = torch.float32)
print(mt)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [11]:
#Setting the device to cuda
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


### Attributes of Tensors

In [15]:
#Attributes of tensors
mt.to(device)
print(mt.dtype)
print(mt.device)
print(mt.shape)
print(mt.requires_grad)

torch.float32
cpu
torch.Size([2, 3])
False


### Other common initialization methods

In [24]:
torch.empty(size = (3,3))

tensor([[242.8989,   0.0000, 248.5073],
        [  0.0000,   1.0000,   1.0000],
        [  1.0000,   1.0000,   1.0000]])

In [25]:
torch.zeros((3,3))


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [26]:
torch.rand((3,3))

tensor([[0.8322, 0.7851, 0.6604],
        [0.0393, 0.1657, 0.8053],
        [0.9678, 0.8182, 0.8179]])

In [27]:
torch.ones((3,3))


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [28]:
torch.eye(5,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [34]:
torch.linspace(start=0.1, end=1, steps=10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [36]:
torch.arange(start = 3, end = 10, step=1)

tensor([3, 4, 5, 6, 7, 8, 9])

In [44]:
torch.empty(size = (1,5)).normal_(mean=0, std = 1)
torch.empty(size=(1,5)).uniform_(0,1)

tensor([[0.9878, 0.1542, 0.6505, 0.1992, 0.8350]])

In [47]:
torch.diag(torch.ones(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### Initialize and convert tensors to different types
    Data-types are :
      1. short() [converts to int16]
      2. long()  [converts to int64]
      3. half()  [converts to float16]
      4. float() [converts to float32]
      5. double() [converts to float64]

In [53]:
tensor = torch.arange(4)
tensor.dtype

torch.int64

In [58]:
tensor.bool()

tensor([False,  True,  True,  True])

In [59]:
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [61]:
tensor.long().dtype

torch.int64

In [62]:
tensor.half().dtype

torch.float16

In [63]:
tensor.float().dtype

torch.float32

In [64]:
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

### Array to tensor conversion

In [65]:
import numpy as np

In [68]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [70]:
tensor  = torch.from_numpy(arr)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [72]:
arr_back = tensor.numpy()
arr_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])