<a href="https://colab.research.google.com/github/taizun-jj202/PyTorch_Basics/blob/basic_ops/TensorIndexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch

In [17]:
batch_size = 10
features = 25

x = torch.rand((batch_size, features))
x[0]


tensor([0.3606, 0.1630, 0.0422, 0.8145, 0.9788, 0.0420, 0.3481, 0.1920, 0.4484,
        0.6007, 0.7563, 0.6342, 0.0129, 0.3698, 0.9410, 0.2155, 0.8499, 0.4030,
        0.9078, 0.5687, 0.3418, 0.7363, 0.0168, 0.7395, 0.2865])

In [18]:
x[:,0]

tensor([0.3606, 0.5116, 0.1194, 0.1004, 0.0242, 0.7661, 0.6945, 0.9445, 0.9104,
        0.0022])

In [19]:
x[2,0:10]

tensor([0.1194, 0.2943, 0.1657, 0.9226, 0.1416, 0.6561, 0.8847, 0.2086, 0.0787,
        0.6916])

In [21]:
# Fancy Indexing
x = torch.arange(10)
print(x)
indices = [2,5,8]
x[indices]

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([2, 5, 8])

In [24]:
x = torch.rand((3,5))
print(x)
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x[rows,cols])

tensor([[0.1056, 0.5548, 0.9353, 0.8041, 0.2163],
        [0.6632, 0.8043, 0.6958, 0.1169, 0.5192],
        [0.2128, 0.9433, 0.3451, 0.5624, 0.1746]])
tensor([0.5192, 0.1056])


In [33]:
#Advanced indexing
x = torch.arange(10)
print(x[ (x < 2) | (x > 8) ])
print( x[ x.remainder(2) == 0 ] )

tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


In [43]:
#  useful operations
print(x)
print(torch.where(x > 5, x, x*2))

print(torch.tensor( [0,0,1,1,2,2,3,4]).unique())
print(x.ndimension())
print(x.numel())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10
